// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspNetCore10WithApacheECharts.Entities
{
    public partial class proc_get_top_countries_salesResult
    {
        [StringLength(300)]
        public string Country { get; set; }
        [Column("Amount", TypeName = "decimal(18,0)")]
        public decimal? Amount { get; set; }
    }
}
